package com.uam.CLINICA.model;

public enum Carrera {
    NOAPLICA,ADMEMPRESAS, ARQUITECTURA, COMUNICACION, DERECHO, DISEÑO, ECONOMIA, 
    INGCIVIL, INGINDUSTRIAL, INGSISTEMAS, MARKETING, MEDICINA, NEGOCIOSINTERNACIONALES, ODONTOLOGIA, 
    POSGRADO, PSICOLOGIA, RELACIONESINT, UAMCOLLEGE 
}
